name: "Deploy"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: web
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nu
        uses: hustcer/setup-nu@v3.8

      - name: Compile
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/timon-schelling/typst:main
          options: -v ${{ github.workspace }}:/data
          run: |
            ls
            ./compile.nu
            cp -r target/* static

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./static

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
